apps/urls.py
from django.urls import path, include
from apps.user import urls as user_urls

urlpatterns = [
    path('', include(user_urls)),
]

apps/user/urls.py
from django.urls import path
from apps.user import views

app_name = "user"
urlpatterns = [
    path('', views.register, name='register'),
    path('validate/', views.validate_code, name='validate-code'),
    path('succes-page/', views.succes_page, name='succes-page'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('apps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block static %} {% endblock static %}
</head>
<body>
{% block content %}

{% endblock content %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% block javascript %}  
{% endblock javascript %}
</body>
</html>

templates/code_validate.html
{% extends 'base.html' %}
{% load static %}
{% block static %} {% endblock static %}
{% block content %}
<div class="main">

    <h1>Sign up</h1>
    <div class="container">
        <div class="sign-up-content">
            <form method="post" action="{% url 'user:validate-code' %}">
                {% csrf_token %}
                <h2 class="form-title">Tasdiqlash kodini kiriting</h2>

                <div class="form-textbox">
                        <label class="form-control-label" for="">Tasdiqlash kodi</label>
                        <input type="text" name="code" value="{{code}}">
                </div><br>


                <div class="form-textbox">
                    <input type="submit" name="submit" class="submit" value="Tasdiqlash" />
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block static %} {% endblock static %}
{% block content %}
    <div class="main">

        <h1>Sign up</h1>
        <div class="container">
            <div class="sign-up-content">
                <form method="post">
                    {% csrf_token %}
                    <h2 class="form-title">Registratsiya qilish</h2>
                   <div class="form-radio" id="radioID">
                       <input type="radio" name="contact" value="phone" id="phone" checked="checked" class="radioBtnClass"/>
                       <label for="phone">Telefon orqali</label>

                       <input type="radio" name="contact" value="email" id="email"  class="radioBtnClass"/>
                        <label for="email">Email orqali</label>
                    </div>

                    <div class="form-textbox">
                        {{ form.fullname.errors }}
                            <label class="form-control-label" for="{{ form.fullname.id_for_label }}">{{ form.fullname.label }}</label>
                        {{ form.fullname }}
                    </div><br>
                    <div class="form-textbox">
                        {{ form.birthday.errors }}
                            <label class="form-control-label" for="{{ form.birthday.id_for_label }}">{{ form.birthday.label }}</label>
                        {{ form.birthday }}
                    </div><br>
                    <div class="form-textbox" id="phone-class">
                        {{ form.phone_number.errors }}
                            <label class="form-control-label" for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}</label>
                        {{ form.phone_number }}
                    </div><br>
                    <div class="form-textbox" style="display: none;" id="email-class">
                        {{ form.email.errors }}
                            <label class="form-control-label" for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                        {{ form.email }}
                    </div><br>

                    <div class="form-textbox">
                        {{ form.password.errors }}
                            <label class="form-control-label" for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                        {{ form.password }}
                    </div><br>



                    <div class="form-group">
                        <input type="checkbox" name="agree-term" id="agree-term" class="agree-term"/>
                        <label for="agree-term" class="label-agree-term"><span><span></span></span>bizning qoidalar bilann tanishib chiqtingizmi?</label>
                    </div>

                    <div class="form-textbox">
                        <input type="submit" name="submit" id="submit" class="submit" value="Create account" disabled="disabled" />
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

{% block javascript %}  

<script>
$('.radioBtnClass').on('click', function () {
    var value = $(this).val();
    if(value === 'email'){
        document.getElementById('email-class').style.display = 'block'
        document.getElementById('phone-class').style.display = 'none'

    }else{
        document.getElementById('email-class').style.display = 'none'
        document.getElementById('phone-class').style.display = 'block'
    }
})
</script>
{% endblock javascript %}

templates/succes.html
{% extends 'base.html' %}
{% load static %}
{% block static %} {% endblock static %}
{% block content %}
<div class="main">

    <h1>Sign up</h1>
    <div class="container">
        <div class="sign-up-content">
            <form method="post" action="{% url 'user:validate-code' %}">
                <h2 class="form-title">Salom {{ user.fullname }} bizning saytka hush kelibsz</h2>
            </form>
        </div>
    </div>

</div>
{% endblock %}